SET( CHECK_HDF4OPEN_SYMBOL
     "1"
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( CHECK_HDF4OPEN_SYMBOL_EXITCODE
     "0"
     CACHE STRING "Output from TRY_RUN" FORCE)

SET( GDAL_HAS_J2K
     "ON"
     CACHE BOOL "Output from TRY_RUN" FORCE)
