# This file is part of MXE.
# See index.html for further information.

FIND_PATH(TIFF_INCLUDE_DIR tiff.h)

FIND_LIBRARY(TIFF_LIBRARY 
             NAMES tiff libtiff_i libtiff tiff3 libtiff3 )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TIFF  DEFAULT_MSG  TIFF_LIBRARY  TIFF_INCLUDE_DIR)

IF(TIFF_FOUND)
  SET( TIFF_LIBRARIES ${TIFF_LIBRARY} )
ENDIF(TIFF_FOUND)

MARK_AS_ADVANCED(TIFF_INCLUDE_DIR TIFF_LIBRARY)
