# This file is part of MXE. See LICENSE.md for licensing information.

PKG             := alembic
$(PKG)_DESCR    := Alembic C++ scene data framework
$(PKG)_WEBSITE  := https://www.alembic.io/
$(PKG)_IGNORE   :=
# Workaround for cross-compilation issue: https://github.com/alembic/alembic/issues/488
$(PKG)_VERSION  := 1.8.11
$(PKG)_CHECKSUM := 2494e5f5195688fe642b21cc9c9ca273908fd327d186d1fe2c2206b7ee010667
$(PKG)_GH_CONF  := hkunz/alembic/tags
$(PKG)_DEPS     := cc imath hdf5 zlib

define $(PKG)_BUILD
    rm -f "$(BUILD_DIR)/CMakeCache.txt"

    cd '$(BUILD_DIR)' && '$(TARGET)-cmake' '$(SOURCE_DIR)' \
        -DCMAKE_INSTALL_PREFIX=$(PREFIX)/$(TARGET) \
        -DBUILD_SHARED_LIBS=$(CMAKE_SHARED_BOOL) \
        -DBUILD_STATIC_LIBS=$(CMAKE_STATIC_BOOL) \
        -DUSE_HDF5=ON \
        -DUSE_PTEX=OFF \
        -DUSE_PRMAN=OFF \
        -DUSE_MAYA=OFF \
        -DUSE_PYTHON=OFF \
        -DHDF5_ROOT=$(PREFIX)/$(TARGET)

    $(MAKE) -C "$(BUILD_DIR)" -j "$(JOBS)"
    $(MAKE) -C "$(BUILD_DIR)" -j 1 install

    # PC file will get generated by: https://github.com/alembic/alembic/issues/491

    # compile test
    '$(TARGET)-g++' \
        '$(TEST_FILE)' \
        -o '$(PREFIX)/$(TARGET)/bin/test-$(PKG).exe' \
        `'$(TARGET)-pkg-config' $(PKG) --cflags --libs`
endef
