# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# _RUN_RESULT_VAR
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set _RUN_RESULT_VAR to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The _COMPILE_RESULT_VAR variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/brand/projects/mxe/mxe/tmp-vmime/kisli-vmime-5f63d47/cmake/cmake-cxx11/Modules/CheckCXX11Features/cxx11-test-__func__.cpp
# Executable    : /home/brand/projects/mxe/mxe/tmp-vmime/kisli-vmime-5f63d47/CMakeFiles/cmTryCompileExec3506745296-_RUN_RESULT_VAR.exe
# Run arguments : 
#    Called from: [2]	/home/brand/projects/mxe/mxe/tmp-vmime/kisli-vmime-5f63d47/cmake/cmake-cxx11/Modules/CheckCXX11Features.cmake
#                 [1]	/home/brand/projects/mxe/mxe/tmp-vmime/kisli-vmime-5f63d47/CMakeLists.txt

SET( _RUN_RESULT_VAR 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

